server:
  port: 8081

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/spring?useUnicode=true&characterEncoding=utf8
    username: root
    password: root
  application:
    name: student-service
  cloud:
    nacos:
      server-addr: localhost:8848
      username: test
      password: test
mybatis:
  configuration:
    map-underscore-to-camel-case: true